name: cyberlang-vpn

services:
  # From https://github.com/linuxserver/docker-wireguard
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      # - SERVERURL=wireguard.domain.com #optional
      # - SERVERPORT=51820 #optional
      # - PEERS=1 #optional
      # - PEERDNS=auto #optional
      # - INTERNAL_SUBNET=10.13.13.0 #optional
      # - ALLOWEDIPS=0.0.0.0/0 #optional
      # - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./wireguard-conf:/config
      # - /lib/modules:/lib/modules #optional
    networks:
      - wgnet
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  app:
    container_name: cyberlang-vpn-app
    build:
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: container:wireguard
    environment:
      - PUID=1000
      - PGID=1000
    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity

networks:
  wgnet:
    driver: bridge
