# These are totally made-up numbers, please change them

timeStart: 2020-01-01
timeStep: 16 # 16 weeks = 4 months
timeRanges:
  - start: k000000
    min: 500
  - start: ka00000
    min: 1000
  - start: kw00000
    min: 400
    end: l000000
